### ISSUE TITLE
Use Ops instead of"Diffraction PSF 3D" command to create PSF

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-scripting#35]
The DeconWithChirpImg.groovy script currently calls `IJ.run("Diffraction PSF 3D", ...)` to create a PSF. But since that script was written, @bnorthan added a `create.kernelDiffraction` op to generate Gibson Lanni kernels based on code from Jizhou Li. So we should update this script accordingly to use it, right?

**Comment by bnorthan** [comment]
Hi @ctrueden 

I just submitted a small pull request which changes the script to use ```create.kernelDiffraction``` .

**Comment by ctrueden** [comment]
Fixed by #36. Thanks, @bnorthan!
