### ISSUE TITLE
kernelGauss refactor breaks tutorial

### ISSUE THREAD

**Issue by kephale** [imagej/imagej-scripting#9]
This commit: https://github.com/imagej/imagej-ops/commit/0cce6f720fbcc34f882002d7c1723793e8138a9e

Breaks this: https://github.com/imagej/imagej-scripting/blob/master/src/main/resources/script_templates/Tutorials/Create_and_Convolve_Points.py#L37

**Comment by ctrueden** [comment]
See also #10

**Comment by ctrueden** [comment]
I believe this was resolved; see conversation in #10.
